name: Workflows Openvpn

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Time
        run: |
          echo "TIME=aniydx/test:$(date +'%Y%m%d')_${{ steps.commit.outputs.short }}" >> $GITHUB_ENV
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        #导入这个模块来完成自动编译和推送
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          # tags: aniydx/test:${{ steps.commit.outputs.short }}
          tags: ${{ env.TIME }}

      # - name: Build Docker image
      #   run:  docker build -t ${{ env.TIME }} .

      # - name: Push  Docker image
      #   run:  docker push ${{ env.TIME }}
